# Generated by Django 5.0.4 on 2024-05-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
